version: "2"
services:
  plex:
    image: linuxserver/plex 
    environment:
    - VERSION=latest
    - TZ=America/New_York
    ports:
    - 32400:32400
    volumes:
    - /home/dev/plex-media/plex/database:/config
    - /home/dev/plex-media/transcode/temp:/transcode
    - /home/dev/plex-media/data/music:/data/music
    - /home/dev/plex-media/data/movies:/data/movies
    - /home/dev/plex-media/data/tvshows:/data/tvshows
    network_mode: "host"

