transmission:
  image: gists/transmission
  ports:
    - "9091:9091"
    - "51413:51413"
    - "51413:51413/udp"
  volumes:
  - /home/dev/transmission-media/data:/data
  environment:
    - USERNAME=dev
    - PASSWORD=blue
  restart: always
