version: "2"
services:
  plex:
    image: plexinc/pms-docker
    environment:
    - TZ=America/New_York
    ports:
    - 32400:32400
    volumes:
    - /home/dev/plex-media/plex/database:/config
    - /home/dev/plex-media/transcode/temp:/transcode
    - /home/dev/plex-media/data:/data